### ISSUE TITLE
convert_units missing in pysm 3

### ISSUE THREAD

**Issue by msyriac** [simonsobs/so_pysm_models#41]
Here's the traceback:

```
$ python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import so_pysm_models
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/global/u2/m/msyriac/repos/so_pysm_models/so_pysm_models/__init__.py", line 36, in <module>
    from .co_lines import COLines
  File "/global/u2/m/msyriac/repos/so_pysm_models/so_pysm_models/co_lines.py", line 5, in <module>
    from pysm import read_map, convert_units
ImportError: cannot import name 'convert_units'

```

**Comment by zonca** [comment]
you are unit the wrong branch:

https://github.com/simonsobs/so_pysm_models/blob/master/so_pysm_models/co_lines.py#L5
